name: Verify

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  verify:
    strategy:
      matrix:
        include:
          - identifier: Windows
            os: windows-latest
  
          - identifier: Ubuntu
            os: ubuntu-latest

          - identifier: MacOS
            os: macos-latest

    name: Verify - ${{ matrix.identifier }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy, llvm-tools-preview
          target: x86_64-unknown-none
          toolchain: nightly

      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@v2

      - name: Verify - Build ${{ matrix.identifier }}
        run: cargo build

      - name: Verify - Clippy
        run: cargo clippy --no-deps -- -Dwarnings